// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAP1F8NJA0cw0r1HH3axKshdtcDPt5oj0',
    appId: '1:658791435452:web:263e8640fa965cddcdd4b9',
    messagingSenderId: '658791435452',
    projectId: 'sample-firebase-ai-app-46c46',
    authDomain: 'sample-firebase-ai-app-46c46.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-46c46.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Fo50N1EQRAGONzgplD1vPYbi1Kp3KYc',
    appId: '1:658791435452:android:fa28680af14669d4cdd4b9',
    messagingSenderId: '658791435452',
    projectId: 'sample-firebase-ai-app-46c46',
    storageBucket: 'sample-firebase-ai-app-46c46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiQcVv9OeE-3Ac4BbK49Lu9WNEBbniTHo',
    appId: '1:658791435452:ios:7680d6ba115f2168cdd4b9',
    messagingSenderId: '658791435452',
    projectId: 'sample-firebase-ai-app-46c46',
    storageBucket: 'sample-firebase-ai-app-46c46.firebasestorage.app',
    iosBundleId: 'com.example.eashtonsfishies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiQcVv9OeE-3Ac4BbK49Lu9WNEBbniTHo',
    appId: '1:658791435452:ios:7680d6ba115f2168cdd4b9',
    messagingSenderId: '658791435452',
    projectId: 'sample-firebase-ai-app-46c46',
    storageBucket: 'sample-firebase-ai-app-46c46.firebasestorage.app',
    iosBundleId: 'com.example.eashtonsfishies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAP1F8NJA0cw0r1HH3axKshdtcDPt5oj0',
    appId: '1:658791435452:web:1eb43f810d24cd16cdd4b9',
    messagingSenderId: '658791435452',
    projectId: 'sample-firebase-ai-app-46c46',
    authDomain: 'sample-firebase-ai-app-46c46.firebaseapp.com',
    storageBucket: 'sample-firebase-ai-app-46c46.firebasestorage.app',
  );
  
}
